"""Vet Disclaimer page."""

import streamlit as st
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utils.styles import inject_css, page_header

inject_css()

page_header("⚕️ Veterinary Disclaimer", "Please read before using this tool.")

sections = [
    (
        "📌 Not a Diagnosis",
        "VetCheck is an informational tool only. The assessments it provides are generated by "
        "placeholder machine-learning models and <strong>do not constitute a veterinary diagnosis</strong>. "
        "Results may be inaccurate, incomplete, or inapplicable to your specific animal's situation.",
    ),
    (
        "👨‍⚕️ Always Consult a Veterinarian",
        "No app, website, or AI tool can replace a qualified, licensed veterinarian. "
        "If your animal is unwell, schedule an in-person appointment. "
        "For emergencies — difficulty breathing, seizures, suspected poisoning, or collapse — "
        "<strong>go to an emergency veterinary clinic immediately</strong>.",
    ),
    (
        "🔒 No Data Storage",
        "This tool does not store any personal information or symptom data entered during a session. "
        "All data is cleared when the browser tab is closed.",
    ),
    (
        "⚠️ Limitation of Liability",
        "The creators of VetCheck accept no liability for decisions made based on results from this tool. "
        "Use of this tool is at the user's own risk.",
    ),
]

for title, body in sections:
    st.markdown(
        f"""<div class="card">
              <h3>{title}</h3>
              <p style="margin:0;color:#4B5563;font-size:0.95rem">{body}</p>
            </div>""",
        unsafe_allow_html=True,
    )

st.markdown("---")
st.markdown(
    "<p style='text-align:center;color:#9CA3AF;font-size:0.8rem'>"
    "VetCheck v0.1 · For educational and development use only · Not for clinical deployment"
    "</p>",
    unsafe_allow_html=True,
)
